const map = {
    javascript: ['https://developer.mozilla.org/en-US/docs/Learn/JavaScript', 'mdn js'],
    java: ['https://docs.oracle.com/javase/8/', 'oracle java'],
    'c#': ['https://msdn.microsoft.com/en-us/library/kx37x362.aspx', 'mdsn'],
    php: ['http://php.net/manual/en/', 'php manual'],
    android: ['https://developer.android.com/guide/index.html', 'android developer'],
    'node.js': ['https://nodejs.org/api/', 'nodejs'],
    'ajax': ['https://developer.mozilla.org/en-US/docs/AJAX', 'mdn ajax'],
    'css': ['https://developer.mozilla.org/en-US/docs/Web/CSS', 'mdn css'],
    'jquery': ['https://jquery.com/', 'jquery'],
    'ios': ['https://developer.apple.com/ios/resources/', 'apple ios'],
    'html': ['https://developer.mozilla.org/en-US/docs/Web/HTML', 'mdn html'],
    'angularjs': ['https://docs.angularjs.org/api', 'angularjs docs'],
    'reactjs': ['https://facebook.github.io/react/', 'react github'],
    'mysql': ['https://dev.mysql.com/doc/', 'mysql'],
    'json': ['http://www.json.org/', 'json.org'],
    'python': ['https://www.python.org/', 'python documentation'],
    'ruby-on-rails': ['http://api.rubyonrails.org/', 'api rubyonrails'],
    'express': ['https://expressjs.com/en/api.html', 'expressjs'],
    'twitter-bootstrap': ['http://bootstrapdocs.com/v3.0.3/docs/css/#overview', 'twitter bootstrap']
}
